# Generated by Django 5.1.7 on 2025-03-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_published_date_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos'),
        ),
    ]
