# Generated by Django 5.1.7 on 2025-03-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagen',
            new_name='image',
        ),
    ]
